---
# deploy.yml

- name: Build and Deploy Configs
  hosts: CAMPUS_FABRIC
  gather_facts: false
  tasks:

    - name: Deploy Configurations to Devices
      import_role:
        name: arista.avd.eos_config_deploy_eapi
